import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar with structured API docs
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 API Documentation',
      items: [
        'api/index',
        'api/overview',
        'api/quick-start',
        'api/api-reference',
        'api/architecture',
        'api/configuration',
        'api/examples',
        'api/troubleshooting',
      ],
    },
  ],

  // Alternative: Auto-generated sidebar (uncomment if preferred)
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
